version: '3.7'

services:
  nginx:
    image: nginx
    init: true
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - NGINX_PORT=80
    volumes:
      - ./dist/:/usr/share/nginx/html/
      - ./meta.conf:/etc/nginx/conf.d/meta.conf
    expose:
      - "80"
    extra_hosts:
      - "example.com:127.0.0.1"
    ports:
      - "80:80"